### ISSUE TITLE
Edson Gano: Feature Request: Mailman as a triggered condition

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/Mailman#177] opened 2017-10-30 17:41 UTC
**Email**
edson.gano@gmail.com

**Description**
We want to be able to use Mailman as an onFormSubmit triggered function; where if a response is submitted or edited, an email is immediately sent out after hitting Submit on the form.

**Comment by dchenier** [comment] 2017-12-05 19:04
Duplicate of #105

**Closed by dchenier** 2017-12-05 19:04 UTC
Labels: user feedback
